#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - development

before_build:
  - nuget restore

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Platypus.sln      # path to Visual Studio solution or project