#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - development

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src/Platypus.sln      # path to Visual Studio solution or project
  
image: Visual Studio 2015
